[global]
keyboard = "en-us"
country  = "us"
fqdn     = "pve01.wgucc.net"
mailto = "mail@no.invalid"
timezone = "America/Los_Angeles"

# Proxmox requires a password during install. We'll lock it immediately at first boot.
# Create a throwaway hash with: mkpasswd --method=yescrypt
root-password-hashed = "$y$j9T$i53YkJW3TvmUWGi/Y2n8O.$.FKLGAQHridjHeo/suwqKyoBHPbbUE8mFvfktrzUWd3"

# Your SSH public keys go straight into /root/.ssh/authorized_keys
root-ssh-keys = [
  "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIK9W3h9Siv1mMFH0X+M0wtD8Oi1/0HfgXrshq2G4T+EJ korin 202509"
]


[network]
# Option A: DHCP network details
#source = "from-dhcp" #use DHCP to get network details

# Option B: static network details (uncomment to use)
source = "from-answer" #use static details
cidr = "104.37.174.28/22"
dns = "1.1.1.1"
gateway = "104.37.172.1"
filter.ID_NET_NAME = "eno1np0" # Dell EMC R750xa onboard NIC 1

[disk-setup]
filesystem = "ext4"
filter-match = "all"
filter.ID_MODEL  = "PERC*" # Dell PERC H730 mini virtual disk
filter.ID_WWN_WITH_EXTENSION="0x644a84202f71f400306703170d0bb434" # Persists across reboots and disk swaps, but will change if array is rebuilt

# LVM sizing 
lvm.swapsize = 8                   # GiB; docs say default is RAM clamped 4–8 GB, set explicitly
lvm.maxroot  = 96                  # GiB for /

[first-boot]
# Run the hardening script immediately once network comes up so it's protected the moment it gets an IP
source   = "from-url"
ordering = "network-online" # wait for network to be online to allow package installs
url = "https://raw.githubusercontent.com/korzynski/proxmox-auto-install/main/hardening.sh"