[global]
keyboard = "en-us"
country  = "us"
fqdn     = "pve01.wgucc.net"
mailto = "mail@no.invalid"
timezone = "America/Los_Angeles"

# Proxmox requires a password during install. We'll lock it immediately at first boot.
# Create a throwaway hash with: mkpasswd --method=yescrypt
root-password-hashed = "$y$j9T$i53YkJW3TvmUWGi/Y2n8O.$.FKLGAQHridjHeo/suwqKyoBHPbbUE8mFvfktrzUWd3"

# Your SSH public keys go straight into /root/.ssh/authorized_keys
root-ssh-keys = [
  "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIK9W3h9Siv1mMFH0X+M0wtD8Oi1/0HfgXrshq2G4T+EJ korin 202509"
]


[network]
# Option A: DHCP network details
source = "from-dhcp" #use DHCP to get network details

# Option B: static network details (uncomment to use)
#source = "from-answer" #use static details below
#cidr = "104.37.174.28/22"
#dns = "1.1.1.1"
#gateway = "104.37.172.1"
#filter.ADDRESS = "24:6e:96:3f:b6:ce"


[disk-setup]
filesystem = "ext4"
lvm.swapsize = 0 # disable swap
lvm.maxvz    = 0 # disable LVM for containers

# Option A: select hardware RAID disk
#filter-match = "all" # all filters must match (default)
#filter.ID_VENDOR = "DELL" # match Dell hardware
#filter.ID_MODEL  = "PERC*"  # match PERC virtual disk model (assumes Dell hardware)
#filter.ID_TYPE   = "disk"   # match only disks (not e.g. CD-ROM)
# Optional extra narrowing if you know it:
# filter.ID_WWN   = "naa.644a8420*"  # use the actual NAA if/when you have it

# Option B: select a specific disk by device name
disk-list = ["sda"]
# filter.DEVLINKS = "*by-id/wwn-0x5000c500aabbccdd*"

[first-boot]
# Run the hardening script before network comes up so it's protected the moment it gets an IP
source   = "from-url"
ordering = "after-network"
url = "https://raw.githubusercontent.com/korzynski/proxmox-auto-install/main/hardening.sh"
cert-fingerprint = "7D:11:22:EA:96:98:52:34:1E:8D:D9:2B:CC:0C:7E:CC:00:96:30:D1:4D:A7:34:D7:CA:42:D5:B5:4A:2B:20:97"